version : '2'

services:
    elasticsearch:
        build: ./ElasticSearchDocker
        volumes:
            - ./ElasticSearchDocker/esdata:/elasticsearch/elasticsearch-5.2.2/data
    
    logstash:
        build: ./LogstashDocker
        volumes:
            - ./LogstashDocker/conf.d:/etc/logstash/conf.d
            - ./LogstashDocker/logs:/logs
        external_links:
            - elasticsearch:elas
        depends_on:
            - elasticsearch

    kibana:
        build: ./KibanaDocker
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
            - logstash
        external_links:
            - elasticsearch:elas

